// Code generated by go-bindata.
// sources:
// conf/conf.dev.toml
// conf/conf.local.toml
// conf/conf.prod.toml
// conf/conf.stg.toml
// DO NOT EDIT!

package bindata

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _confConfDevToml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x54\xcd\x4d\x0a\xc2\x40\x0c\x47\xf1\x7d\x4e\x11\x66\x29\xf4\x63\xd9\x4d\x4f\x52\x64\x88\x65\x88\x03\xd1\xfc\x99\x0c\x7a\x7d\xa9\x0a\xe2\xfe\xc7\x7b\x9b\xb9\x6a\x69\x67\x12\x20\x9b\x6b\x86\xf4\x2b\x33\xf3\xca\x69\xea\x37\x4c\xea\x83\x60\xb8\x48\x94\x51\x80\xd1\x5c\x13\xc9\xbe\x97\x88\x1f\xff\xb3\xf5\x8b\xdf\xe6\xe3\x69\x8b\xd2\x1e\xc7\x05\xde\x3a\xaf\xbc\xcc\xcb\x4c\x62\xe6\xcf\xec\xad\x6a\xbd\x1f\x89\x53\xa2\x57\x00\x00\x00\xff\xff\x87\xd5\x1e\xf9\x8e\x00\x00\x00")

func confConfDevTomlBytes() ([]byte, error) {
	return bindataRead(
		_confConfDevToml,
		"conf/conf.dev.toml",
	)
}

func confConfDevToml() (*asset, error) {
	bytes, err := confConfDevTomlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "conf/conf.dev.toml", size: 142, mode: os.FileMode(420), modTime: time.Unix(1552580426, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _confConfLocalToml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x54\xcd\x4d\x0a\xc2\x40\x0c\x47\xf1\x7d\x4e\x11\x66\x29\xf4\x63\xd9\x4d\x4f\x52\x64\x88\x65\x88\x03\xd1\xfc\x99\x0c\x7a\x7d\xa9\x0a\xe2\xfe\xc7\x7b\x9b\xb9\x6a\x69\x67\x12\x20\x9b\x6b\x86\xf4\x2b\x33\xf3\xca\x69\xea\x37\x4c\xea\x83\x60\xb8\x48\x94\x51\x80\xd1\x5c\x13\xc9\xbe\x97\x88\x1f\xff\xb3\xf5\x8b\xdf\xe6\xe3\x69\x8b\xd2\x1e\xc7\x05\xde\x3a\xaf\xbc\xcc\xcb\x4c\x62\xe6\xcf\xec\xad\x6a\xbd\x1f\x89\x53\xa2\x57\x00\x00\x00\xff\xff\x87\xd5\x1e\xf9\x8e\x00\x00\x00")

func confConfLocalTomlBytes() ([]byte, error) {
	return bindataRead(
		_confConfLocalToml,
		"conf/conf.local.toml",
	)
}

func confConfLocalToml() (*asset, error) {
	bytes, err := confConfLocalTomlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "conf/conf.local.toml", size: 142, mode: os.FileMode(420), modTime: time.Unix(1552580426, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _confConfProdToml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x54\xcd\x4d\x0a\xc2\x40\x0c\x47\xf1\x7d\x4e\x11\x66\x29\xf4\x63\xd9\x4d\x4f\x52\x64\x88\x65\x88\x03\xd1\xfc\x99\x0c\x7a\x7d\xa9\x0a\xe2\xfe\xc7\x7b\x9b\xb9\x6a\x69\x67\x12\x20\x9b\x6b\x86\xf4\x2b\x33\xf3\xca\x69\xea\x37\x4c\xea\x83\x60\xb8\x48\x94\x51\x80\xd1\x5c\x13\xc9\xbe\x97\x88\x1f\xff\xb3\xf5\x8b\xdf\xe6\xe3\x69\x8b\xd2\x1e\xc7\x05\xde\x3a\xaf\xbc\xcc\xcb\x4c\x62\xe6\xcf\xec\xad\x6a\xbd\x1f\x89\x53\xa2\x57\x00\x00\x00\xff\xff\x87\xd5\x1e\xf9\x8e\x00\x00\x00")

func confConfProdTomlBytes() ([]byte, error) {
	return bindataRead(
		_confConfProdToml,
		"conf/conf.prod.toml",
	)
}

func confConfProdToml() (*asset, error) {
	bytes, err := confConfProdTomlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "conf/conf.prod.toml", size: 142, mode: os.FileMode(420), modTime: time.Unix(1552580426, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _confConfStgToml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x54\xcd\x4d\x0a\xc2\x40\x0c\x47\xf1\x7d\x4e\x11\x66\x29\xf4\x63\xd9\x4d\x4f\x52\x64\x88\x65\x88\x03\xd1\xfc\x99\x0c\x7a\x7d\xa9\x0a\xe2\xfe\xc7\x7b\x9b\xb9\x6a\x69\x67\x12\x20\x9b\x6b\x86\xf4\x2b\x33\xf3\xca\x69\xea\x37\x4c\xea\x83\x60\xb8\x48\x94\x51\x80\xd1\x5c\x13\xc9\xbe\x97\x88\x1f\xff\xb3\xf5\x8b\xdf\xe6\xe3\x69\x8b\xd2\x1e\xc7\x05\xde\x3a\xaf\xbc\xcc\xcb\x4c\x62\xe6\xcf\xec\xad\x6a\xbd\x1f\x89\x53\xa2\x57\x00\x00\x00\xff\xff\x87\xd5\x1e\xf9\x8e\x00\x00\x00")

func confConfStgTomlBytes() ([]byte, error) {
	return bindataRead(
		_confConfStgToml,
		"conf/conf.stg.toml",
	)
}

func confConfStgToml() (*asset, error) {
	bytes, err := confConfStgTomlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "conf/conf.stg.toml", size: 142, mode: os.FileMode(420), modTime: time.Unix(1552580426, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"conf/conf.dev.toml": confConfDevToml,
	"conf/conf.local.toml": confConfLocalToml,
	"conf/conf.prod.toml": confConfProdToml,
	"conf/conf.stg.toml": confConfStgToml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"conf": &bintree{nil, map[string]*bintree{
		"conf.dev.toml": &bintree{confConfDevToml, map[string]*bintree{}},
		"conf.local.toml": &bintree{confConfLocalToml, map[string]*bintree{}},
		"conf.prod.toml": &bintree{confConfProdToml, map[string]*bintree{}},
		"conf.stg.toml": &bintree{confConfStgToml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

